# Generated by Django 4.2.27 on 2026-01-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search_lawyer', '0002_rename_speciality_lawyer_specialty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('package_type', models.CharField(choices=[('document', 'Document handling'), ('consultation', 'Consultation only'), ('court', 'Court appearance')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='search_lawyer.lawyer')),
            ],
        ),
    ]
