# Generated by Django 4.2.27 on 2026-01-10 15:33

from django.db import migrations


def add_packages(apps, schema_editor):
    ConsultationPackage = apps.get_model(
        'consultation_packages', 'ConsultationPackage'
    )

    ConsultationPackage.objects.bulk_create([
        ConsultationPackage(
            title="Quick Legal Consultation (15 mins)",
            package_type="Consultation",
            description="Ideal for quick legal questions and basic guidance over call or video.",
            max_price=20.00
        ),
        ConsultationPackage(
            title="Standard Legal Consultation (30 mins)",
            package_type="Consultation",
            description="Detailed discussion with a lawyer for civil, criminal, or family matters.",
            max_price=40.00
        ),
        ConsultationPackage(
            title="Legal Document Drafting & Review",
            package_type="document",
            description="Drafting or review of agreements, affidavits, notices, or legal documents.",
            min_price=100.00,
            max_price=200.00
        ),
        ConsultationPackage(
            title="Property & Agreement Verification",
            package_type="document",
            description="Verification of property papers, sale deeds, rental agreements, and compliance.",
            min_price=200.00,
            max_price=700.00
        ),
        ConsultationPackage(
            title="Court Appearance & Representation",
            package_type="court",
            description="Lawyer appearance before court for hearings, filings, or case representation.",
            min_price=300.00,
            max_price=1000.00
        ),
    ])




class Migration(migrations.Migration):

    dependencies = [
        ('consultation_packages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_packages),
    ]
