# Generated by Django 4.2.27 on 2026-01-31 15:58

from django.db import migrations




def create_packages(apps, schema_editor):
    ConsultationPackage = apps.get_model('consultation_packages', 'ConsultationPackage')
    Lawyer = apps.get_model('search_lawyer', 'Lawyer')

    # Example: get a lawyer safely
    lawyer = Lawyer.objects.first()
    if not lawyer:
        return

    packages = [

        {
                        
            "title": "Quick Legal Consultation (15 mins)",
            "package_type": "Consultation",
            "description": "Ideal for quick legal questions and basic guidance over call or video.",
            "min_price": 0.00,
            "max_price": 20.00,
            "lawyer": lawyer,
        },

        {
           
           
            "title": "Standard Legal Consultation (30 mins)",
            "package_type": "Consultation",
            "description": "Detailed discussion with a lawyer for civil, criminal, or family matters.",
            "min_price": 0.00,
            "max_price": 40.00,
            "lawyer": lawyer,

        },

        {
            "title": "Legal Document Drafting & Review",
            "package_type": "document",
            "description": "Drafting or review of agreements, affidavits, notices, or legal documents.",
            "min_price": 100.00,
            "max_price": 200.00,
            "lawyer": lawyer,
        },
        {
            "title": "Property & Agreement Verification",
            "package_type": "document",
            "description": "Verification of property papers, sale deeds, rental agreements, and compliance.",
            "min_price": 200.00,
            "max_price": 700.00,
            "lawyer": lawyer,
        },
        {
            "title": "Court Appearance & Representation",
            "package_type": "court",
            "description": "Lawyer appearance before court for hearings, filings, or case representation.",
            "min_price": 300.00,
            "max_price": 1000.00,
            "lawyer": lawyer,
        },

    ]

    for package in packages:
        ConsultationPackage.objects.get_or_create(
            title=package["title"],
            lawyer=package["lawyer"],
            defaults=package,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('search_lawyer', '0006_alter_lawyer_slug'),
        ('consultation_packages', '0002_seed_consultation_packages'),
    ]

    operations = [
        migrations.RunPython(create_packages),


    ]
