# Generated by Django 4.2.27 on 2026-01-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('consultation_package', 'Consultation Package'), ('subscription', 'Subscription')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_plan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
