# Generated by Django 4.2.27 on 2026-01-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_payment_type_payment_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('consultation_package', 'Consultation_Package'), ('subscription', 'Subscription')], max_length=20, null=True),
        ),
    ]
