# Generated by Django 4.2.27 on 2025-12-12 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lawyer_type', models.CharField(choices=[('solicitor', 'Solicitor'), ('advocate', 'Advocate')], max_length=20)),
                ('speciality', models.CharField(blank=True, choices=[('contracts', 'Contracts'), ('deeds', 'Deeds'), ('family', 'Family'), ('commercial', 'Commercial'), ('criminal', 'Criminal')], max_length=50, null=True)),
                ('court_level', models.CharField(blank=True, choices=[('magistrate', "Magistrate's Court"), ('high', 'High Court'), ('appeal', 'Appeal Court')], max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
