# Generated by Django 4.2.27 on 2026-01-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_lawyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer',
            old_name='speciality',
            new_name='specialty',
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='lawyer_type',
            field=models.CharField(blank=True, choices=[('solicitor', 'Solicitor'), ('advocate', 'Advocate')], max_length=20, null=True),
        ),
    ]
