# Generated by Django 4.2.27 on 2026-01-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_lawyer', '0002_rename_speciality_lawyer_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='lawyers/'),
        ),
    ]
