# Generated by Django 4.2.27 on 2026-01-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_lawyer', '0003_lawyer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
