# Generated by Django 4.2.27 on 2026-01-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_lawyer', '0004_lawyer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
