# Generated by Django 4.2.27 on 2026-01-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_lawyer', '0005_alter_lawyer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
