# Generated by Django 4.2.27 on 2026-04-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_lawyer', '0006_alter_lawyer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
